# Generated by Django 3.2.6 on 2021-08-21 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique id for the event')),
                ('name', models.CharField(max_length=255, verbose_name='Event name')),
            ],
        ),
    ]
