# Generated by Django 3.2.6 on 2021-08-22 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDateVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique id for the event voter')),
                ('name', models.CharField(max_length=255, verbose_name='Event voter name')),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique id for the event / date connection')),
                ('date', models.DateField(verbose_name='Suitable date for the event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('voters', models.ManyToManyField(blank=True, to='event.EventDateVoter')),
            ],
        ),
    ]
